### ISSUE TITLE
Build fails with "error: trampoline generated for nested function"

### ISSUE THREAD

**Issue by muflax** [basic-gongfu/cixl#14]
Build fails on gcc 6.4.0 on Gentoo/Linux (specifically, with `gcc --version`: `Gentoo 6.4.0-r1 p1.3`):

    $ make
    
    Scanning dependencies of target libcixl
    [  0%] Building C object CMakeFiles/libcixl.dir/src/cixl/arg.c.o
    [...]/cixl/src/cixl/arg.c: In function ‘cx_resolve_arg_refs’:
    [...]/cixl/src/cixl/arg.c:160:18: error: trampoline generated for nested function ‘get_tt_arg’ [-Werror=trampolines]
      struct cx_type *get_tt_arg(int i) {
                      ^~~~~~~~~~
    cc1: all warnings being treated as errors
    make[2]: *** [CMakeFiles/libcixl.dir/build.make:63: CMakeFiles/libcixl.dir/src/cixl/arg.c.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/libcixl.dir/all] Error 2
    make: *** [Makefile:130: all] Error 2

There's a few more trampoline warnings, that's just the first one. Skimming the code, they mostly seem to result from closures in various argument parsing functions?

Gentoo enables `-Wtrampolines` in gcc by default. Adding `-Wno-error=trampolines` allows cixl to build, tests pass, everything seems fine. 

The warning was added around gcc 4.x because trampolines can force the stack to be executable. They're also less portable in general.

**Comment by basic-gongfu** [comment]
Noted, thanks.
I find this too specific for the readme, but it's about time I got a wiki up and running anyway.
