### ISSUE TITLE
build fails on FreeBSD

### ISSUE THREAD

**Issue by crcx** [basic-gongfu/cixl#5]
Build fails on FreeBSD 11 with the following errors:

~~~
/home/crc/src/rune/cixl-master/src/cixl/libs/rec.c:94:55: error: function
      definition is not allowed here
  bool push_type(struct cx_type *t, int row, int col) {
                                                      ^
/home/crc/src/rune/cixl-master/src/cixl/libs/rec.c:117:7: error: implicit
      declaration of function 'push_type' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        if (!push_type(&rec_type->imp, t->row, t->col)) { goto exit4; }
             ^
2 errors generated.
~~~

**Comment by basic-gongfu** [comment]
That looks like it doesn't like nested functions, which is a GNU extension. First thing I would try is to switch compiler to GCC as some Clang installations seem to come without support.

**Comment by ephetic** [comment]
The clang docs say they do not and will never support nested functions (in really surprisingly harsh language).

**Comment by basic-gongfu** [comment]
That's just stupid, but GCC it is then; I've updated the make file and readme to reflect the change.
